# Generated by Django 4.2.25 on 2025-12-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.RemoveField(
            model_name='activity',
            name='notification_enabled',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.AddField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(default='10:00:00'),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
