# Generated by Django 4.2.25 on 2025-12-14 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['-priority', 'name']},
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='link',
        ),
        migrations.RemoveField(
            model_name='emergencycontact',
            name='phone',
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='phone_number',
            field=models.CharField(default='000-000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='priority',
            field=models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='name',
            field=models.CharField(default='Unnamed Contact', max_length=200),
        ),
    ]
